// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: EdFuelspj

#include "../ui.h"

void ui_screenButtons_screen_init(void)
{
    ui_screenButtons = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenButtons, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_screenButtons, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_screenButtons, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);

    ui_btnStream = ui_TextButton_create(ui_screenButtons);
    lv_obj_set_x(ui_btnStream, 0);
    lv_obj_set_y(ui_btnStream, 0);

    lv_label_set_text(ui_comp_get_child(ui_btnStream, UI_COMP_TEXTBUTTON_LBLTEXT), "Stream");

    ui_TextButton1 = ui_TextButton_create(ui_screenButtons);
    lv_obj_set_x(ui_TextButton1, 0);
    lv_obj_set_y(ui_TextButton1, 0);

    lv_label_set_text(ui_comp_get_child(ui_TextButton1, UI_COMP_TEXTBUTTON_LBLTEXT), "Record");

    ui_TextButton2 = ui_TextButton_create(ui_screenButtons);
    lv_obj_set_x(ui_TextButton2, 0);
    lv_obj_set_y(ui_TextButton2, 0);

    lv_label_set_text(ui_comp_get_child(ui_TextButton2, UI_COMP_TEXTBUTTON_LBLTEXT), "Replay");

    ui_TextButton3 = ui_TextButton_create(ui_screenButtons);
    lv_obj_set_x(ui_TextButton3, 0);
    lv_obj_set_y(ui_TextButton3, 0);

    lv_label_set_text(ui_comp_get_child(ui_TextButton3, UI_COMP_TEXTBUTTON_LBLTEXT), "Replay Save");

    lv_obj_add_event_cb(ui_btnStream, ui_event_btnStream_TextButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextButton1, ui_event_TextButton1_TextButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextButton2, ui_event_TextButton2_TextButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextButton3, ui_event_TextButton3_TextButton, LV_EVENT_ALL, NULL);

}
