// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: EdFuelspj

#include "../ui.h"

void ui_scrPloatformioOTA_screen_init(void)
{
    ui_scrPloatformioOTA = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrPloatformioOTA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel8 = lv_obj_create(ui_scrPloatformioOTA);
    lv_obj_set_width(ui_Panel8, 240);
    lv_obj_set_height(ui_Panel8, 78);
    lv_obj_set_x(ui_Panel8, 1);
    lv_obj_set_y(ui_Panel8, 0);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x9E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel8, lv_color_hex(0x9F4747), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "platformIO\nOTA");
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblPlatformIOOTA = lv_label_create(ui_scrPloatformioOTA);
    lv_obj_set_width(ui_lblPlatformIOOTA, 210);
    lv_obj_set_height(ui_lblPlatformIOOTA, lv_pct(72));
    lv_obj_set_x(ui_lblPlatformIOOTA, 1);
    lv_obj_set_y(ui_lblPlatformIOOTA, 37);
    lv_obj_set_align(ui_lblPlatformIOOTA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPlatformIOOTA, "OTA for platformIO\nuploading @\n#0000ff *IP*#");
    lv_label_set_recolor(ui_lblPlatformIOOTA, "true");
    lv_obj_clear_flag(ui_lblPlatformIOOTA,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_lblPlatformIOOTA, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_align(ui_lblPlatformIOOTA, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblPlatformIOOTA, &ui_font_Eurose16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel8, ui_event_Panel8, LV_EVENT_ALL, NULL);

}
