// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: EdFuelspj

#include "../ui.h"

void ui_screenWiFiConfig_screen_init(void)
{
    ui_screenWiFiConfig = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenWiFiConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_screenWiFiConfig, &ui_img_1367923625, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_screenWiFiConfig, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screenWiFiConfig_Container2 = lv_obj_create(ui_screenWiFiConfig);
    lv_obj_remove_style_all(ui_screenWiFiConfig_Container2);
    lv_obj_set_width(ui_screenWiFiConfig_Container2, 240);
    lv_obj_set_height(ui_screenWiFiConfig_Container2, 315);
    lv_obj_set_align(ui_screenWiFiConfig_Container2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_screenWiFiConfig_Container2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_screenWiFiConfig_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_screenWiFiConfig_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_screenWiFiConfig_Panel1 = lv_obj_create(ui_screenWiFiConfig_Container2);
    lv_obj_set_width(ui_screenWiFiConfig_Panel1, 240);
    lv_obj_set_height(ui_screenWiFiConfig_Panel1, 47);
    lv_obj_set_align(ui_screenWiFiConfig_Panel1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_screenWiFiConfig_Panel1,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_screenWiFiConfig_Panel1, lv_color_hex(0x9E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenWiFiConfig_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screenWiFiConfig_Label3 = lv_label_create(ui_screenWiFiConfig_Panel1);
    lv_obj_set_width(ui_screenWiFiConfig_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_screenWiFiConfig_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_screenWiFiConfig_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_screenWiFiConfig_Label3, "Wifi Config");
    lv_obj_set_style_text_font(ui_screenWiFiConfig_Label3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screenWiFiConfig_Panel3 = lv_obj_create(ui_screenWiFiConfig_Container2);
    lv_obj_set_width(ui_screenWiFiConfig_Panel3, 237);
    lv_obj_set_height(ui_screenWiFiConfig_Panel3, 266);
    lv_obj_set_align(ui_screenWiFiConfig_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_screenWiFiConfig_Panel3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_screenWiFiConfig_Panel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_screenWiFiConfig_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenWiFiConfig_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenWiFiConfig_Panel3, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screenWiFiConfig_lblWifiInfo = lv_label_create(ui_screenWiFiConfig_Panel3);
    lv_obj_set_width(ui_screenWiFiConfig_lblWifiInfo, 216);
    lv_obj_set_height(ui_screenWiFiConfig_lblWifiInfo, lv_pct(97));
    lv_obj_set_x(ui_screenWiFiConfig_lblWifiInfo, 2);
    lv_obj_set_y(ui_screenWiFiConfig_lblWifiInfo, -143);
    lv_obj_set_align(ui_screenWiFiConfig_lblWifiInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_screenWiFiConfig_lblWifiInfo,
                      "Connect Phone/Computer to WiFi Acess point #ff0000 EDFuelGauge#\npassword: #ff0000 *PASS*#\n\naccess web page \n#0000ff http://192.168.4.1/config# in browser\n\nFill Out the fields");
    lv_label_set_recolor(ui_screenWiFiConfig_lblWifiInfo, "true");
    lv_obj_clear_flag(ui_screenWiFiConfig_lblWifiInfo,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_screenWiFiConfig_lblWifiInfo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

}
