// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: EdFuelspj

#ifndef _UI_COMP_TEXTBUTTON_H
#define _UI_COMP_TEXTBUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT TextButton
#define UI_COMP_TEXTBUTTON_TEXTBUTTON 0
#define UI_COMP_TEXTBUTTON_LBLTEXT 1
#define _UI_COMP_TEXTBUTTON_NUM 2
lv_obj_t * ui_TextButton_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
