// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: EdFuelspj

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenFuel
void ui_ScreenFuel_screen_init(void);
lv_obj_t * ui_ScreenFuel;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Panel6;
void ui_event_lblShipName(lv_event_t * e);
lv_obj_t * ui_lblShipName;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Container5;
lv_obj_t * ui_lblMainFuel;
lv_obj_t * ui_brMain;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Container7;
lv_obj_t * ui_lblResFuel;
lv_obj_t * ui_brRes;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_spinCharging;
lv_obj_t * ui_spinLowFuel;
lv_obj_t * ui_cntDimmer;


// SCREEN: ui_screenWiFiConfig
void ui_screenWiFiConfig_screen_init(void);
lv_obj_t * ui_screenWiFiConfig;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_lblWifiInfo;


// SCREEN: ui_screenWaitingForData
void ui_screenWaitingForData_screen_init(void);
lv_obj_t * ui_screenWaitingForData;
lv_obj_t * ui_Container8;
void ui_event_Panel2(lv_event_t * e);
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_lblWaiting;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_lblShipName(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenWaitingForData, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenWaitingForData_screen_init);
    }
}
void ui_event_Panel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenFuel, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenFuel_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenFuel_screen_init();
    ui_screenWiFiConfig_screen_init();
    ui_screenWaitingForData_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenFuel);
}
