// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: EdFuelspj

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenFuel
void ui_ScreenFuel_screen_init(void);
void ui_event_ScreenFuel(lv_event_t * e);
lv_obj_t * ui_ScreenFuel;
lv_obj_t * ui_ScreenFuel_Container1;
lv_obj_t * ui_ScreenFuel_Panel6;
void ui_event_ScreenFuel_lblShipName(lv_event_t * e);
lv_obj_t * ui_ScreenFuel_lblShipName;
lv_obj_t * ui_ScreenFuel_Container4;
lv_obj_t * ui_ScreenFuel_Label1;
lv_obj_t * ui_ScreenFuel_Container5;
lv_obj_t * ui_ScreenFuel_lblMainFuel;
lv_obj_t * ui_ScreenFuel_brMain;
lv_obj_t * ui_ScreenFuel_Container6;
lv_obj_t * ui_ScreenFuel_Label2;
lv_obj_t * ui_ScreenFuel_Container7;
lv_obj_t * ui_ScreenFuel_lblResFuel;
lv_obj_t * ui_ScreenFuel_brRes;
lv_obj_t * ui_ScreenFuel_Container3;
lv_obj_t * ui_ScreenFuel_Panel4;
lv_obj_t * ui_ScreenFuel_spinCharging;
lv_obj_t * ui_ScreenFuel_spinLowFuel;


// SCREEN: ui_screenWiFiConfig
void ui_screenWiFiConfig_screen_init(void);
lv_obj_t * ui_screenWiFiConfig;
lv_obj_t * ui_screenWiFiConfig_Container2;
lv_obj_t * ui_screenWiFiConfig_Panel1;
lv_obj_t * ui_screenWiFiConfig_Label3;
lv_obj_t * ui_screenWiFiConfig_Panel3;
lv_obj_t * ui_screenWiFiConfig_lblWifiInfo;


// SCREEN: ui_screenWaitingForData
void ui_screenWaitingForData_screen_init(void);
void ui_event_screenWaitingForData(lv_event_t * e);
lv_obj_t * ui_screenWaitingForData;
lv_obj_t * ui_screenWaitingForData_Container8;
void ui_event_screenWaitingForData_Panel2(lv_event_t * e);
lv_obj_t * ui_screenWaitingForData_Panel2;
lv_obj_t * ui_screenWaitingForData_Label5;
lv_obj_t * ui_screenWaitingForData_Panel5;
lv_obj_t * ui_screenWaitingForData_lblWaiting;


// SCREEN: ui_screenButtons
void ui_screenButtons_screen_init(void);
void ui_event_screenButtons(lv_event_t * e);
lv_obj_t * ui_screenButtons;
lv_obj_t * ui_screenButtons_Panel7;
lv_obj_t * ui_screenButtons_btnsOnbtn;
void ui_event_screenButtons_Label4(lv_event_t * e);
lv_obj_t * ui_screenButtons_Label4;
void ui_event_screenButtons_arcBOn(lv_event_t * e);
lv_obj_t * ui_screenButtons_arcBOn;
lv_obj_t * ui_screenButtons_Panel8;
lv_obj_t * ui_screenButtons_Button3;
void ui_event_screenButtons_Label6(lv_event_t * e);
lv_obj_t * ui_screenButtons_Label6;
void ui_event_screenButtons_arcBOff(lv_event_t * e);
lv_obj_t * ui_screenButtons_arcBOff;
void ui_event_screenButtons_btnSave(lv_event_t * e);
lv_obj_t * ui_screenButtons_btnSave;
lv_obj_t * ui_screenButtons_Label7;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenFuel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_screenButtons, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_screenButtons_screen_init);
        prevScreenFuel(e);
    }
}
void ui_event_ScreenFuel_lblShipName(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenWaitingForData, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenWaitingForData_screen_init);
    }
}
void ui_event_screenWaitingForData(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_screenButtons, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_screenButtons_screen_init);
        setFromScreenWaiting(e);
    }
}
void ui_event_screenWaitingForData_Panel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenFuel, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenFuel_screen_init);
    }
}
void ui_event_screenButtons(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        procscrbtnsGesture(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        procBtnsShow(e);
    }
}
void ui_event_screenButtons_Label4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lblBOnCB(e);
    }
}
void ui_event_screenButtons_arcBOn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        procArcBOnChanged(e);
    }
}
void ui_event_screenButtons_Label6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lblBOffCB(e);
    }
}
void ui_event_screenButtons_arcBOff(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        procArcBOffChanged(e);
    }
}
void ui_event_screenButtons_btnSave(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        procBtnsSave(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenFuel_screen_init();
    ui_screenWiFiConfig_screen_init();
    ui_screenWaitingForData_screen_init();
    ui_screenButtons_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenFuel);
}
