// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: EdFuelspj

#ifndef _EDFUELSPJ_UI_H
#define _EDFUELSPJ_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_ScreenFuel
void ui_ScreenFuel_screen_init(void);
void ui_event_ScreenFuel(lv_event_t * e);
extern lv_obj_t * ui_ScreenFuel;
extern lv_obj_t * ui_ScreenFuel_Container1;
extern lv_obj_t * ui_ScreenFuel_Panel6;
void ui_event_ScreenFuel_lblShipName(lv_event_t * e);
extern lv_obj_t * ui_ScreenFuel_lblShipName;
extern lv_obj_t * ui_ScreenFuel_Container4;
extern lv_obj_t * ui_ScreenFuel_Label1;
extern lv_obj_t * ui_ScreenFuel_Container5;
extern lv_obj_t * ui_ScreenFuel_lblMainFuel;
extern lv_obj_t * ui_ScreenFuel_brMain;
extern lv_obj_t * ui_ScreenFuel_Container6;
extern lv_obj_t * ui_ScreenFuel_Label2;
extern lv_obj_t * ui_ScreenFuel_Container7;
extern lv_obj_t * ui_ScreenFuel_lblResFuel;
extern lv_obj_t * ui_ScreenFuel_brRes;
extern lv_obj_t * ui_ScreenFuel_Container3;
extern lv_obj_t * ui_ScreenFuel_Panel4;
extern lv_obj_t * ui_ScreenFuel_spinCharging;
extern lv_obj_t * ui_ScreenFuel_spinLowFuel;
// SCREEN: ui_screenWiFiConfig
void ui_screenWiFiConfig_screen_init(void);
extern lv_obj_t * ui_screenWiFiConfig;
extern lv_obj_t * ui_screenWiFiConfig_Container2;
extern lv_obj_t * ui_screenWiFiConfig_Panel1;
extern lv_obj_t * ui_screenWiFiConfig_Label3;
extern lv_obj_t * ui_screenWiFiConfig_Panel3;
extern lv_obj_t * ui_screenWiFiConfig_lblWifiInfo;
// SCREEN: ui_screenWaitingForData
void ui_screenWaitingForData_screen_init(void);
void ui_event_screenWaitingForData(lv_event_t * e);
extern lv_obj_t * ui_screenWaitingForData;
extern lv_obj_t * ui_screenWaitingForData_Container8;
void ui_event_screenWaitingForData_Panel2(lv_event_t * e);
extern lv_obj_t * ui_screenWaitingForData_Panel2;
extern lv_obj_t * ui_screenWaitingForData_Label5;
extern lv_obj_t * ui_screenWaitingForData_Panel5;
extern lv_obj_t * ui_screenWaitingForData_lblWaiting;
// SCREEN: ui_screenButtons
void ui_screenButtons_screen_init(void);
void ui_event_screenButtons(lv_event_t * e);
extern lv_obj_t * ui_screenButtons;
extern lv_obj_t * ui_screenButtons_Panel7;
extern lv_obj_t * ui_screenButtons_btnsOnbtn;
void ui_event_screenButtons_Label4(lv_event_t * e);
extern lv_obj_t * ui_screenButtons_Label4;
void ui_event_screenButtons_arcBOn(lv_event_t * e);
extern lv_obj_t * ui_screenButtons_arcBOn;
extern lv_obj_t * ui_screenButtons_Panel8;
extern lv_obj_t * ui_screenButtons_Button3;
void ui_event_screenButtons_Label6(lv_event_t * e);
extern lv_obj_t * ui_screenButtons_Label6;
void ui_event_screenButtons_arcBOff(lv_event_t * e);
extern lv_obj_t * ui_screenButtons_arcBOff;
void ui_event_screenButtons_btnSave(lv_event_t * e);
extern lv_obj_t * ui_screenButtons_btnSave;
extern lv_obj_t * ui_screenButtons_Label7;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1367923625);    // assets/elite-dangerous-logo.png



LV_FONT_DECLARE(ui_font_Eurose16);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
