// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: EdFuelspj

#ifndef _EDFUELSPJ_UI_H
#define _EDFUELSPJ_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenFuel
void ui_ScreenFuel_screen_init(void);
extern lv_obj_t * ui_ScreenFuel;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Panel6;
void ui_event_lblShipName(lv_event_t * e);
extern lv_obj_t * ui_lblShipName;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_lblMainFuel;
extern lv_obj_t * ui_brMain;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_lblResFuel;
extern lv_obj_t * ui_brRes;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_spinCharging;
extern lv_obj_t * ui_spinLowFuel;
extern lv_obj_t * ui_cntDimmer;
// SCREEN: ui_screenWiFiConfig
void ui_screenWiFiConfig_screen_init(void);
extern lv_obj_t * ui_screenWiFiConfig;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_lblWifiInfo;
// SCREEN: ui_screenWaitingForData
void ui_screenWaitingForData_screen_init(void);
extern lv_obj_t * ui_screenWaitingForData;
extern lv_obj_t * ui_Container8;
void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_lblWaiting;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1367923625);    // assets/elite-dangerous-logo.png



LV_FONT_DECLARE(ui_font_Eurose16);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
