// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: EdFuelspj

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void prevScreenFuel(lv_event_t * e);
void setFromScreenWaiting(lv_event_t * e);
void procscrbtnsGesture(lv_event_t * e);
void procBtnsShow(lv_event_t * e);
void lblBOnCB(lv_event_t * e);
void procArcBOnChanged(lv_event_t * e);
void lblBOffCB(lv_event_t * e);
void procArcBOffChanged(lv_event_t * e);
void procBtnsSave(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
