// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: EdFuelspj

#include "ui.h"

void evtHandle_btnStream(lv_event_t * e)
{
	// Your code here
}

void evtHandle_btnRecord(lv_event_t * e)
{
	// Your code here
}

void evtHandle_btnReplay(lv_event_t * e)
{
	// Your code here
}

void evtHandle_btnReplaySave(lv_event_t * e)
{
	// Your code here
}
